import * as Icons from "developer-icons";

export const skills = [
  { Icon: Icons.HTML5, title: "html" },
  { Icon: Icons.CSS3, title: "css" },
  { Icon: Icons.JavaScript, title: "javascript" },
  { Icon: Icons.TypeScript, title: "typescript" },
  { Icon: Icons.ESLint, title: "ESLint" },
  { Icon: Icons.Prettier, title: "prettier" },
  { Icon: Icons.Jest, title: "jest" },
  { Icon: Icons.Python, title: "python" },
  { Icon: Icons.Dart, title: "dart" },
  { Icon: Icons.React, title: "react js" },
  { Icon: Icons.NextJs, title: "next js" },
  { Icon: Icons.Redux, title: "Redux" },
  { Icon: Icons.FramerDark, DarkIcon: Icons.FramerLight, title: "framer" },
  { Icon: Icons.PWA, title: "PWA" },
  { Icon: Icons.Flutter, title: "flutter" },
  { Icon: Icons.NodeJs, title: "node js" },
  { Icon: Icons.ExpressJsDark, DarkIcon: Icons.ExpressJsLight, title: "express js" },
  { Icon: Icons.NestJS, title: "nest js" },
  { Icon: Icons.MongoDB, title: "mongodb" },
  { Icon: Icons.Firebase, title: "Firebase" },
  { Icon: Icons.Docker, title: "Docker" },
  { Icon: Icons.Terraform, title: "terraform" },
  { Icon: Icons.Redis, title: "Redis" },
  { Icon: Icons.AWS, title: "AWS" },
  { Icon: Icons.GoogleCloud, title: "GCP" },
  { Icon: Icons.VercelDark, DarkIcon: Icons.VercelLight, title: "vercel" },
  { Icon: Icons.Heroku, title: "heroku" },
  { Icon: Icons.Git, title: "git" },
  { Icon: Icons.Postman, title: "postman" },
  { Icon: Icons.Figma, title: "figma" },
];
